import React, { useState, useEffect, useRef } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { HomeWrapper } from "./styledComponents";
import useColor from "../hooks/useColor";

const Wish = () => {
  const router = useRouter();
  const { slug } = router.query;
  const { currentColor } = useColor();
  return (
    <div>
      <Head>
        <title>Happy New Year</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeWrapper bgColor={currentColor}>
        {/* {history[0] == "/" ? (
            <Button
              onClick={() => {
                setDownloadedOnce(false);
                setDownloading(true);
              }}
              text="Download as Image"
            />
          ) : (
            ""
          )}

          <Button
            onClick={() => router.push("/")}
            text="&larr; Create a wish"
          /> */}
        <p>Made by Anil</p>
      </HomeWrapper>
      {/* <audio ref={audioRef} id="player" autoPlay>
        <source src="media/hbd.mp3" />
      </audio> */}
    </div>
  );
};

export default Wish;
