import type { NextPage } from "next";
import Head from "next/head";
import { colors } from "../constants/colors";
import useColor from "../hooks/useColor";
import styles from "../styles/Home.module.css";
import {
  Color,
  ColorSelector,
  ColorSelectorContainer,
  CreateWishText,
  FieldsContainer,
  Heading,
  HomeWrapper,
  NameInput,
} from "./styledComponents";

const Home: NextPage = () => {
  const { currentColor, setColor } = useColor();
  return (
    <>
      <Head>
        <title>New Year Wish - Anil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Patua+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      <HomeWrapper>
        <Heading>Welcome!</Heading>
        <FieldsContainer>
          <CreateWishText>Create a new year wish here.</CreateWishText>
          <NameInput placeholder="Enter the name here" autoFocus={true} />

          <ColorSelectorContainer>
            <ColorSelector onChange={(e: any) => setColor(e.target.id)}>
              {colors.map((color) => (
                <Color
                  key={color.id}
                  type="radio"
                  color={color.color}
                  id={color.id.toString()}
                  name="color"
                  value={color.color}
                  defaultChecked={currentColor.id === color.id}
                />
              ))}
            </ColorSelector>
          </ColorSelectorContainer>
        </FieldsContainer>

        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer> */}
      </HomeWrapper>
    </>
  );
};

export default Home;
