import type { NextPage } from "next";
import Head from "next/head";
import {
  CreateWishText,
  FieldsContainer,
  Heading,
  HomeWrapper,
  NameInput,
} from "./styledComponents";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>New Year Wish -Anil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Patua+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      <HomeWrapper>
        <Heading>Welcome!</Heading>
        <FieldsContainer>
          <CreateWishText>Create a new year wish here.</CreateWishText>
          <NameInput placeholder="Enter the name here" autoFocus={true} />
        </FieldsContainer>

        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer> */}
      </HomeWrapper>
    </>
  );
};

export default Home;
