import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";
import { motion } from "framer-motion";

import useColor from "../hooks/useColor";
import { variants } from "../utils/MotionUtils";
import Footer from "../components/Footer";
import {
	CreateWishText,
	FieldsContainer,
	Heading,
	HomeWrapper,
	NameInput,
	CreateWishButton,
} from "../styles/styledComponents";

const Home: NextPage = () => {
	const { currentColor, setColor } = useColor();
	const [name, setName] = useState("");
	const router = useRouter();
	const handleInput = (e: React.ChangeEvent<HTMLInputElement>) => {
		setName(e.target.value);
	};

	const handleNameSubmit = () => {
		if (!name || name === " ") {
			alert("Please enter a name!");
			return;
		} else router.push(`/${name}`);
	};

	return (
		<>
			<Head>
				<title>New Year Wish By Anil</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' />
				<link
					href='https://fonts.googleapis.com/css2?family=Patua+One&display=swap'
					rel='stylesheet'
				/>
			</Head>

			<HomeWrapper theme={currentColor}>
				<FieldsContainer>
					<motion.div initial='hidden' animate='visible' variants={variants}>
						<Heading className='title'>Welcome!</Heading>
					</motion.div>
					<CreateWishText>Create a new year wish here.</CreateWishText>
					<NameInput
						placeholder='Ex: Anil Chowdary'
						autoFocus={true}
						value={name}
						onChange={handleInput}
					/>
					<CreateWishButton onClick={handleNameSubmit}>Create</CreateWishButton>
				</FieldsContainer>
				<Footer />
			</HomeWrapper>
		</>
	);
};

export default Home;
